config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#index'

  resources :users, only: [:show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resource :like, only: [:create, :destroy], controller: 'likes'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  validates :text, presence: true

  after_save :update_comment_counter

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_like_counter

  def update_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: :post_id
  has_many :likes, foreign_key: :post_id
  has_many :users, through: :likes
  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  after_save :update_post_counter
  # A method that updates the posts counter for a user.
  def update_post_counter
    author.increment!(:posts_counter)
  end

  # A method which returns the 5 most recent comments for a given post.
  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  has_many :liked_posts, through: :likes, source: :post
  validates :name, presence: true
  validates :photo, presence: true
  validates :bio, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        @current_user ||= User.first
    end
end

app/controllers/comments_controller.rb
class LikesController < ActionController::Base
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      render 'posts/show'
    end
  end

  def create
    @like = Like.new(like_params)
    @like.save
    redirect_to likes_path
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy
    redirect_to likes_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/likes_controller.rb
 class LikesController < ApplicationController
  before_action :find_post

    def create
      @like = @post.likes.build(user_id: current_user.id)
  
      if @like.save
        redirect_to @post, notice: 'Post liked!'
      else
        redirect_to @post, alert: 'Unable to like the post.'
      end
    end
  
    def destroy
      like = @post.likes.find_by(user_id: current_user.id)
      like.destroy if like
      redirect_to @post, notice: 'Post unliked!'
    end
  
    private

    def find_post
      @post = Post.find(params[:post_id])
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.author
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post = @user.posts.order(created_at: :desc).limit(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/new.html.erb
<%= form_with model: @comment, url: comments_path do |form| %>
    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>
  
    <%= form.submit "Create Comment" %>
  <% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/hello.html.erb
<h1>Hello World</h1>
<p>Find me in app/views/pages/hello.html.erb</p>

app/views/partials/_comment.html.erb
<ul class='comment-content'>
<% comments.each do |comment|%>
<li><%= comment.author.name%>: <%=comment.text%></li>
<%end%>
<%= 'No comments' if comments.empty?%>
</ul>

app/views/partials/_post.html.erb
# <%=link_to user_post_path(post.author, post), class:'post-content' do%>
    <div class='post_subcont'>
        <h3><%=post.title%></h3>
        <div><%=post.text[0, 100]%><%='...' if post.text[51]%></div>
        <p class='post-total'>Comments: <%=post.comments_counter%>, Likes: <%=post.likes_counter%></p>
    </div>
    # <%end%>
    

app/views/partials/_user.html.erb
<% if user.present? %>
<div class="user-card">
  <div class="user-photo-box">
    <img src="<%= user.photo %>" alt="User photo" class="user-photo">
  </div>
  <div class="user-details">
    <h3 class="user-name"><%= user.name %></h3>
    <small>Number of posts: <%= user.posts.length %></small>
  </div>
</div>
<% else %>
  <p>User not found.</p>
<% end %>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<%= render 'partials/user', user: @user %>

<% @posts.each_with_index do |post, index| %>
    <a href="/users/<%= post.author.id %>/posts/<%= post.id %>">
      <div class="container recent_post">
        <p class="post-num">Post #<%= index + 1 %></p>
        <p class="post-title"><%= post.title %></p>
      <small class="counters">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></small>

      <% if post.recent_comments.length.positive? %>
        <div class="comment-card">
          <h3>Comments</h3>
          <% post.recent_comments.each do |comment| %>
            <p><%= comment.author.name %>: <%= comment.text %> </p>
          <% end %>
        </div>
      <% end %>
    </div>
  </a>
<% end %>

app/views/posts/new.html.erb
<%= form_with model: @post, url: posts_path do |form| %>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="field">
      <%= form.label :text %>
      <%= form.text_area :text %>
    </div>
  
    <%= form.submit "Create Post" %>
  <% end %>
  

app/views/posts/show.html.erb
<h1>Post Details</h1>
<div class="detailed-post-box container">
  <div class="username-and-counters">
    <p class="dp-username">Post #1 by <%= @user.name %></p>
    <small class="dp-counters">Comments: <%= @post.comments.length %>, Likes: <%= @post.likes.length %></small>
  </div>

  <%= form_with model: @like, url: post_likes_path(@post), method: :post do |form| %>
    <%= form.submit "Like" %>
  <% end %>

  <p class="dp-text"><%= @post.text %></p>

  <div class="dp-comments comment-card">
    <h3>Comments</h3>
    <% if !@post.comments.length.positive? %>
      <p>No comments yet</p>
    <% end %>

    <% @post.comments.each do |comment| %>
      <p><%= comment.author.name %>: <%= comment.text %> </p>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<ul>
  <% if @users.present? %>
    <% @users.each do |user| %>
      <li>
        <a href='users/<%= user.id %>'><%= render 'partials/user', user: user %></a>
      </li>
    <% end %>
  <% else %>
    <li>No users found.</li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1>User Details</h1>
<%= render 'partials/user', user: @user %>

<div class="bio-card container">
  <h3 class="bio-card-header">Bio</h3>
  <p><%= @user.bio %> </p>
</div>

<% @post.each_with_index do |post, index| %>
    # <a href="/users/<%= @user.id %>/posts/<%= post.id %>">
    <%= render 'partials/post', post: post %>
  <% end %>  

<div class="btn-div">
  <a href="<%= @user.id %>/posts" class="see-all-posts">See all posts</a>
</div>